name: doctor_finder_flutter
description: A Flutter app to find doctors nearby with appointments and reviews.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.5

  # State Management
  provider: ^6.0.5

  # Google Maps
  google_maps_flutter: ^2.5.0
  geolocator: ^9.0.2
  permission_handler: ^10.4.3

  # UI Components
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1

  # Navigation
  go_router: ^10.1.2

  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  # Assets section
  assets:
    - assets/images/logo.png
    - assets/images/doctor-placeholder.png