// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjn6D2MIelGDwnleVX3kXausuz5slswKY',
    appId: '1:489321981801:web:42934440d9f31c2b213ff8',
    messagingSenderId: '489321981801',
    projectId: 'doctor-finder-b94c2',
    authDomain: 'doctor-finder-b94c2.firebaseapp.com',
    storageBucket: 'doctor-finder-b94c2.firebasestorage.app',
    measurementId: 'G-X8K4NHY9YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB65GTDUOZTSYN6BylZhv5wTu_Ji6GLOOg',
    appId: '1:489321981801:android:7348d7050e4e3bf0213ff8',
    messagingSenderId: '489321981801',
    projectId: 'doctor-finder-b94c2',
    storageBucket: 'doctor-finder-b94c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlasSvs0uytp6fNsSosgG41ppg0f8QKyQ',
    appId: '1:489321981801:ios:1761ce9e4ebef981213ff8',
    messagingSenderId: '489321981801',
    projectId: 'doctor-finder-b94c2',
    storageBucket: 'doctor-finder-b94c2.firebasestorage.app',
    iosBundleId: 'com.example.doctorFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlasSvs0uytp6fNsSosgG41ppg0f8QKyQ',
    appId: '1:489321981801:ios:1761ce9e4ebef981213ff8',
    messagingSenderId: '489321981801',
    projectId: 'doctor-finder-b94c2',
    storageBucket: 'doctor-finder-b94c2.firebasestorage.app',
    iosBundleId: 'com.example.doctorFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjn6D2MIelGDwnleVX3kXausuz5slswKY',
    appId: '1:489321981801:web:3eb62979d13055bd213ff8',
    messagingSenderId: '489321981801',
    projectId: 'doctor-finder-b94c2',
    authDomain: 'doctor-finder-b94c2.firebaseapp.com',
    storageBucket: 'doctor-finder-b94c2.firebasestorage.app',
    measurementId: 'G-YVVD3XHCWK',
  );

}